steps:
  - name: "gcr.io/cloud-builders/gcloud"
    waitFor: ["-"]
    args:
      [
        "functions",
        "deploy",
        "offer_search_trigger",
        "--source",
        "https://source.developers.google.com/projects/${PROJECT_ID}/repos/${REPO_NAME}/revisions/${REVISION_ID}",
        "--trigger-event",
        "providers/google.firebase.database/eventTypes/ref.create",
        "--trigger-resource",
        "projects/_/instances/panprices/refs/offers/SE/{searchID}",
        "--region",
        "europe-west1",
        "--runtime",
        "python37",
        "--vpc-connector=k8s-connector",
        "--set-env-vars",
        "_FERNET_SECRET_KEY=${_FERNET_SECRET_KEY}",
      ]

  - name: "gcr.io/cloud-builders/gcloud"
    waitFor: ["-"]
    args:
      [
        "functions",
        "deploy",
        "live_search_offer_enricher",
        "--source",
        "https://source.developers.google.com/projects/${PROJECT_ID}/repos/${REPO_NAME}/revisions/${REVISION_ID}",
        "--trigger-topic",
        "live_search_offers",
        "--region",
        "europe-west1",
        "--runtime",
        "python37",
        "--vpc-connector=k8s-connector",
        "--max-instances",
        "50",
      ]

  - name: "gcr.io/cloud-builders/gcloud"
    waitFor: ["-"]
    args:
      [
        "functions",
        "deploy",
        "sherlock_shopping_finish_signal",
        "--source",
        "https://source.developers.google.com/projects/${PROJECT_ID}/repos/${REPO_NAME}/revisions/${REVISION_ID}",
        "--trigger-topic",
        "sherlock_google_shopping_finished",
        "--region",
        "europe-west1",
        "--runtime",
        "python37",
      ]

  - name: "gcr.io/cloud-builders/gcloud"
    waitFor: ["-"]
    args:
      [
        "functions",
        "deploy",
        "delete_old_firebase_data",
        "--source",
        "https://source.developers.google.com/projects/${PROJECT_ID}/repos/${REPO_NAME}/revisions/${REVISION_ID}",
        "--trigger-topic",
        "trigger_delete_old_firebase_data",
        "--region",
        "europe-west1",
        "--runtime",
        "python37",
        "--timeout",
        "540s",
        "--memory",
        "1GB",
      ]

  - name: "gcr.io/cloud-builders/gcloud"
    waitFor: ["-"]
    args:
      [
        "functions",
        "deploy",
        "popular_product_search_trigger",
        "--source",
        "https://source.developers.google.com/projects/${PROJECT_ID}/repos/${REPO_NAME}/revisions/${REVISION_ID}",
        "--trigger-topic",
        "trigger_fetching_popular_products",
        "--region",
        "europe-west1",
        "--runtime",
        "python37",
        "--vpc-connector=k8s-connector",
        "--timeout",
        "540s",
      ]

  - name: "gcr.io/cloud-builders/gcloud"
    waitFor: ["-"]
    args:
      [
        "functions",
        "deploy",
        "get_price_from_firebase",
        "--source",
        "https://source.developers.google.com/projects/${PROJECT_ID}/repos/${REPO_NAME}/revisions/${REVISION_ID}",
        "--trigger-http",
        "--region",
        "europe-west1",
        "--runtime",
        "python37",
        "--max-instances",
        "1",
        "--allow-unauthenticated",
      ]

  - name: "gcr.io/cloud-builders/gcloud"
    waitFor: ["-"]
    args:
      [
        "functions",
        "deploy",
        "create_offer_firebase",
        "--source",
        "https://source.developers.google.com/projects/${PROJECT_ID}/repos/${REPO_NAME}/revisions/${REVISION_ID}",
        "--trigger-http",
        "--region",
        "europe-west1",
        "--runtime",
        "python37",
        "--allow-unauthenticated",
      ]

  - name: "gcr.io/cloud-builders/gcloud"
    waitFor: ["-"]
    args:
      [
        "functions",
        "deploy",
        "create_product_search_firebase",
        "--source",
        "https://source.developers.google.com/projects/${PROJECT_ID}/repos/${REPO_NAME}/revisions/${REVISION_ID}",
        "--trigger-http",
        "--region",
        "europe-west1",
        "--runtime",
        "python37",
        "--allow-unauthenticated",
      ]

images: []
timeout: "1600s"
